### ISSUE TITLE
有没有人有邀请码分享下

### ISSUE THREAD

**Issue by cicar-coll** [ZCSSR/url#2]

**Comment by heny** [comment]
https://zcssr.cc/auth/register?code=r9ch

**Comment by realliuzenan** [comment]
https://zcssr.cc/auth/register?code=5lfD

**Comment by 312767908** [comment]
点击获取邀请码https://zcssr.fun/auth/register?code=EyjO

**Comment by ZpLucas** [comment]
kyRO

**Comment by wsdragon** [comment]
https://zcssr.com/auth/register?code=JA1o

**Comment by wsdragon** [comment]
https://zc18.xyz/auth/register?code=JA1o

**Comment by wsdragon** [comment]
邀请码 JA1o
